#!/bin/sh 
# - BOOTSTRAP TERMUX SETUP
# - Auto install list of packages
# TODO
# - Add prompts to confirm actions.. Or to begin
# - Perhaps a set of initial prompts to trigger each section on or off..
# - LINK FARM. script to make links after termux-setup-storage, core dirs into home dire
# - zsh powerlevel10k setup 
# - modify above to install powerlevel 10k and then use the location based on whether using termux..

# pkg setup
apt-get update # update package lists
pkg upgrade
cat $HOME/.config/termux/pkgs.termux.pkg.txt | xargs pkg install
cat $HOME/.config/termux/pkgs.termux.apt.txt | xargs apt-get install -y
cat $HOME/.config/termux/pkgs.termux.pip.txt | xargs pip install -y
# APT?
# Command which filters out matching patterns..?


# pull repos

cd $HOME
git clone ssh://git@github.com/futuresurf/cfg .config.new
mv .config .delete-config
mv .config.new .config

git clone ssh://git@github.com/futuresurf/cfgb .local/bin.new
mv .local/bin .delete-bin
mv .local/bin.new .local/bin

git clone ssh://git@github.com/futuresurf/dd


# configure home

chsh -s zsh
termux-setup-storage


# zsh theme

pkgdir=$HOME/.local/pkg
[[ -d $pkgdir ]] || mkdir $pkgdir
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.local/pkg/powerlevel10k


# other

nvim -c 'PlugInstall'

