#!/bin/env bash

# IAROM MADDEN mail@iarom.org

# - [ ] how can i package personal programs distinct from git projects?
# reduce dependency on pulling multiple and entire git repo's.
# instead just pull a repo full of the built up to date progs?

trx_cfg_dir="${HOME}/.xx/cfb/zu-ctrl/linux-termux"
trx_rpo="/dat/ud/deva/trx"
ipi=$(cat "${ssh_cfg_dir}/host-i" 2>/dev/null)

sshd_pass_switch()
{
    printf "%s\n" \
        "PrintMotd yes" \
        "PasswordAuthentication ${1} " \
        "Subsystem sftp /data/data/com.termux/files/usr/libexec/sftp-server" \
        > "/data/data/com.termux/files/usr/etc/ssh/sshd_config"
}

git_clone() { [ -d "${2}" ] || git clone "${1}" "${2}"; }

bootstrap_from_linux()
{
    # run from linux machine after ssh key exchange
    rsync -avz "${trx_rpo}" ${ipi}:~/.local/pkg/trx/
    
    ssh ${ipi} 'cd ~/.local/pkg/trx && make install-termux'
    ssh ${ipi} 'cat .ssh/id_ed25519.pub' |\
        gh ssh-key add - --title "${ipi}"
    
    echo "execute the following on termux to proceed"
    echo "2) on termux: termux-change-repo"
    echo "3) on termux: termux-setup-storage"
    read -r -p "completed? (y/n)" answer
    
    if [[ ${answer} =~ "y" ]]; then
        # - [ ] execute 'ssh dev-name "trx bootstrap"'
    else
        echo "above actions are required before proceeding"
    fi
}

bootstrap_clone()
{
    git_clone "git@github.com:iarxm/cfa.git"   "${HOME}/.xx/cfa"
    git_clone "git@github.com:iarxm/cfb.git"   "${HOME}/.xx/cfb"
    git_clone "git@github.com:iarxm/sh.git"    "${HOME}/.xx/bin"
    git_clone "git@github.com:iarxm/dd.git"    "${HOME}/da"
    git_clone "git@github.com:iarxm/uboot.git" "${HOME}/.local/pkg/uboot"
}

bootstrap_ins_nvim()
{
    #rsync 
    nvim --headless -c 'Lazy sync' +qa
}

bootstrap_ins()
{
    pkg install -y $(< "${trx_cfg_dir}/pkg-man.txt")
    pip install -y $(< "${trx_cfg_dir}/pkg-pip.txt")
    bootstrap_ins_nvim
    lng termux
}

bootstrap_cfg()
{
    sshd_pass_switch "no"
}

bootstrap()
{
    # - [ ] keep init bootstrap in uboot and keep public
    # - [ ] zsh powerlevel10k setup 
    # - [x] LINK FARM (after termux-setup-storage)
    bootstrap_clone
    bootstrap_install
    bootstrap_cfg
}

adb_cfg_neutron()
{
    adb shell settings put secure icon_blacklist hotspot,mobile,battery
}

main()
{
    case ${cmd} in
        adb-cfg)              adb_cfg_neutron ;;
        sshd-p-on)            sshd_pass_switch "yes" ;;
        sshd-p-off)           sshd_pass_switch "no" ;;
        ssh-copyid)           ssh-copy-id -p 8022 "${ipi}" ;;
        bootstrap-lnx)        bootstrap_from_linux "${@}" ;;
        bootstrap)            bootstrap ;;
    esac
}

main "${@}"
