#!/bin/bash
# - Sets up ip bridging between linux and termux
# - Push ip address to remote repo from termux
# - Pull it from linux
#

ip_dir="$HOME/.local/share/aax/trx"
ip_file="ip.dr.wlan"
ip_file_all="ip.dr.all"
ip_path="$ip_dir/$ip_file"

cd "$ip_dir" 
ip=$(ifconfig | grep -Eo 'inet (192\.168\.)[0-9]*\.[0-9]*' | sed -E 's/inet //g')

printf "%s \n" "wlan ip: $ip"
printf "%s" "$ip" > $ip_file
printf "$ip ---> $ip_file \n"

git commit $ip_file -m "updating wlan ip file of droid device"
git push

